
## GitLab CE image
## ref: https://hub.docker.com/r/gitlab/gitlab-ce/tags/
##
image: gitlab/gitlab-ce:9.4.1-ce.0

imagePullPolicy: IfNotPresent

externalUrl: http://gitlab.mytest.io/

gitlabRootPassword: "gitlab123456"

serviceType: NodePort

## Ingress configuration options
##
ingress:
  annotations:
#      kubernetes.io/ingress.class: nginx
#      kubernetes.io/tls-acme: "true"
  enabled: false
  tls:
#    - secretName: tls-gitlab-ingress
#      hosts:
#      - gitlab.mytest.io
  url: gitlab.mytest.io


persistence:
  gitlabEtc:
    enabled: true
    size: 1Gi
    storageClass: "gitlab-data"
    accessMode: ReadWriteOnce

  gitlabData:
    enabled: true
    size: 10Gi
    storageClass: "gitlab-data"
    accessMode: ReadWriteOnce

postgresql:
  # 9.6 is the newest supported version for the GitLab container
  imageTag: "9.6"
  cpu: 1000m
  memory: 1Gi

  postgresUser: gitlab
  postgresPassword: gitlab
  postgresDatabase: gitlab

  persistence:
    storageClass: "gitlab-data"
    size: 10Gi

redis:
  redisPassword: "gitlab"

  resources:
    requests:
      memory: 1Gi

  persistence:
    storageClass: "gitlab-data"
    size: 10Gi
