apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins2-lb
  namespace: kube-ops
spec:
  rules:
  - hosts: jenkins.mytest.io
    http:
      paths:
      - backend:
        serviceName: jenkins2
        servicePort: 8080