apiVersion: v1
appVersion: 12.0.3
description: Handling incoming emails
home: https://about.gitlab.com/
icon: https://gitlab.com/gitlab-com/gitlab-artwork/raw/master/logo/logo-square.svg
keywords:
- gitlab
- mailroom
maintainers:
- email: support@gitlab.com
  name: GitLab Inc.
name: mailroom
sources:
- https://gitlab.com/charts/gitlab/tree/master/charts/gitlab/charts/mailroom
- https://gitlab.com/gitlab-org/build/CNG/tree/master/gitlab-mailroom
version: 2.0.3
