apiVersion: v1
kind: ServiceAccount
metadata:
  name: ops
  namespace: kube-ops
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ops-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: ops
  namespace: kube-ops
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
